
spring.datasource.url=jdbc:mysql://10.10.182.6:3306/porschegt3cup?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=bruno
spring.datasource.password=bsdnadmin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

server.port=8085